name: flutter_learn_getx
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  d_info: ^0.2.2
  d_input: ^0.1.2
  d_method: ^0.2.4
  flutter:
    sdk: flutter
  get: ^4.6.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
